#!/bin/sh
# Copyright (C) 2016 Intel
# Licensed on MIT

ostree_enabled() {
	return 0
}

ostree_run() {
    mount -t efivarfs efivarfs /sys/firmware/efi/efivars
    mount --bind /rootfs/ostree/deploy/poky/deploy/*.0 /rootfs/
}
